PEN-1355-Dev platform ALB stack
whcc/platform-alb-cdk pull request #2
Opened 2024-03-12 14:18 UTC by bil-sukhtsooj

## Summary
Ticket: https://whcc.atlassian.net/browse/PEN-1355

Created stack for dev internal apps.

## AWS
Created following resources:
1. Load balancer
- HTTP Port 80 listener
- HTTPS Port 443 listener
- Added rules to each listener, same as existing Prod internal-alb listeners

2024-03-12 14:34 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +        alb.ListenerCondition.pathPatterns(['/']),
OPEN QUESTION - Do we need separate rules for path pattern `/` vs `/*`?

2024-03-15 03:21 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    const certificateArn = 'arn:aws:acm:us-east-2:799497006720:certificate/ce6306c4-27ee-4d93-b12a-fafab73552af'; // TODO
@bil-sukhtsooj Can this cart ARN go in config json?

2024-03-15 03:22 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +        alb.ListenerCondition.pathPatterns(['/']),
To clarify, this question does not need to be resolve in order to merge this PR.

2024-03-15 03:23 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    const devInternalSecurityGroup = new ec2.SecurityGroup(this, 'devInternalSecurityGroup', { vpc, allowAllOutbound: true, securityGroupName: props.namingBuilder.GetAwsNaming('alb-security-group')})
NIT: Can you put these object properties on separate lines like the others?

2024-03-15 03:24 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    const alertBackendServiceArn = "arn:aws:sns:us-east-2:799497006720:alerts-backend-services";
I think this should go in config json too.

2024-03-15 03:25 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    const alertBackendServiceArn = "arn:aws:sns:us-east-2:799497006720:alerts-backend-services";
Or...what is the case to leave it in here vs config json?

2024-03-15 03:27 UTC, andrew-merkouris-whcc requested changes
Nice job on this @bil-sukhtsooj. I added some minor feedback / questions.

Let's review tomorrow. I think it's worth going slow and figuring out the right patterns for this before we create the prod ALBs.

2024-03-15 14:25 UTC, bil-sukhtsooj commented
Discussed with @andrew-merkouris-whcc. This PR is scoped to Dev stack and won't have changes for established patterns for upcoming Prod and Sandbox.

2024-03-15 14:35 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +    const alertBackendServiceArn = "arn:aws:sns:us-east-2:799497006720:alerts-backend-services";
Addressed this in slack. This'll be separate story.

2024-03-15 14:35 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +    const certificateArn = 'arn:aws:acm:us-east-2:799497006720:certificate/ce6306c4-27ee-4d93-b12a-fafab73552af'; // TODO
Addressed this in slack. This'll be separate story.

2024-03-15 14:40 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +    const devInternalSecurityGroup = new ec2.SecurityGroup(this, 'devInternalSecurityGroup', { vpc, allowAllOutbound: true, securityGroupName: props.namingBuilder.GetAwsNaming('alb-security-group')})
Lines separated

2024-03-15 16:25 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    const certificateArn = 'arn:aws:acm:us-east-2:799497006720:certificate/ce6306c4-27ee-4d93-b12a-fafab73552af'; // TODO
@bil-sukhtsooj and I chatted about this. He will move the 3 hard-coded ARNs into platform-alb-cdk.ts.

2024-03-15 16:37 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +        alb.ListenerCondition.pathPatterns(['/']),
Spike created: https://whcc.atlassian.net/browse/PEN-1368

2024-03-15 16:59 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +    const certificateArn = 'arn:aws:acm:us-east-2:799497006720:certificate/ce6306c4-27ee-4d93-b12a-fafab73552af'; // TODO
Moved values to constants

2024-03-18 15:46 UTC, matthew-macgregor commented on lib/platform-alb-stack.ts
> +        alb.ListenerCondition.pathPatterns(['/']),
You shouldn't need to specify path patterns at all unless you need to route to a different target group for a path. Generically, it's useful to think about how the rules get evaluated: like a switch/case, and a default at the bottom.

Whichever case matches first is where the request is routed.

2024-03-18 17:10 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    httpListener.addAction('httpGpIntAction', {
@matthew-macgregor Unfortunately we have several apps making requests to GPInt with a non-https url.

Here are the existing listener rules of `arn:aws:elasticloadbalancing:us-east-2:835299498740:listener/app/alb-internal-apps/c50be40fc10e9f9d/cb824c4727eff57f` -

![image](https://github.com/whcc/platform-alb-cdk/assets/96845762/1783d74b-c43d-469a-ae9b-2127fa09c162)

2024-03-18 17:14 UTC, andrew-merkouris-whcc commented on lib/platform-alb-stack.ts
> +    httpsListener.addAction('httpsProdpiLoginAction', {
Agreed, we should only have one target group for `login`. (Current platform prod external ALB has separate target groups, and we copied that configuration).

2024-03-19 14:21 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +      comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_OR_EQUAL_TO_THRESHOLD,
No reason. I collapsed these to loop

2024-03-19 14:24 UTC, bil-sukhtsooj commented on lib/platform-alb-stack.ts
> +    httpsListener.addAction('httpsProdpiLoginAction', {
As Per comment above I have:
1. I removed all path patterns as suggested, since we don't need it.
2. Removed `Prodpi` target group, since we don't have Dev `Prodpi`

2024-03-19 14:31 UTC, chrishanline commented
> Since this is just dev at the moment, what is the plan for sandbox/prod? It seems like we would want them all to use exactly the same stack with different configuration data?

resurfacing this -- I'm a bit concerned with the various items with `dev` in the name. changing CDK names after the fact can be painful and it seems like we should be setting this up to be a bit more config data focused?

2024-03-19 16:24 UTC, PatrickNiesen commented
Can we add .nvmrc file to specify the node version we want to target? This will ensure we have a repeatable deployment run even if newer versions of NodeJS come out that might break this stack in the future. 

Example .nvmrc file
https://github.com/whcc/cdk_template/blob/main/cdk/.nvmrc

I would then add a `nvm install` as the first step of the README.md. Node Version Manager(NVM) will change/install the specified version

2024-03-20 12:18 UTC, cliff-robbins-whcc commented
@bil-sukhtsooj I agree with Matthew.  The current stack is heavily focused on dev.  You need to abstract that out and have those values unique to dev go into the dev config.

This is a good start; however, its not ready to deploy.

2024-03-20 14:00 UTC, bil-sukhtsooj commented
There is a separate ticket for establishing data driven pattern for this Repo. https://whcc.atlassian.net/browse/PEN-1374
In this PR, my thought was to get review on the resources and make sure I got the resources correct. I won't be deploying this PR.
There'll be PR that'll branch off of this branch for the other change, FIY

2024-03-20 15:00 UTC, andrew-merkouris-whcc commented
> why you wouldn't just add the resource to the config then with this PR.

@cliff-robbins-whcc We had to determine what resources we needed to create via CDK to recreate everything needed in the platform load balancers. I consider this PR an incremental deliverable - @bil-sukhtsooj created a working ALB in `platform-dev` via CDK. Next step is to move as much as we can into config json (and Bil was just saying he'll likely create a separate branch off of this to start that work).

We would also like review on the physical resources that were created. How does everything look on `arn:aws:elasticloadbalancing:us-east-2:799497006720:loadbalancer/app/platform-internal-alb-dev-ue2/2942d622bd1b08c2`

2024-03-20 21:13 UTC, cliff-robbins-whcc commented
> We would also like review on the physical resources that were created. How does everything look on `arn:aws:elasticloadbalancing:us-east-2:799497006720:loadbalancer/app/platform-internal-alb-dev-ue2/2942d622bd1b08c2`?

@andrew-merkouris-whcc the target groups don't look correct.  I see the new target groups; however, the ip addresses are wrong for each target group.
The instance 10.32.26.180 is not coming up when I do a nslookup.

2024-03-25 16:28 UTC, closed without merging